#!usr/bin/env python
#-*- coding:utf-8 _*-
"""
@author:alvin
@file: f1.py
@time: 2019/01/10
"""
import  requests
# cert  443       verify
r = requests.get(url="https://www.12306.cn/index/",verify=False)
#text 乱码的使用 content（二进制）解码输出
print(r.content.decode('utf-8'))
